reads/urls.py
from django.conf.urls import url

from . import views

app_name = 'reads'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<book_id>[0-9]+)/$', views.detail, name='detail')
]

runnerreads/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^reads/', include('reads.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^v1/api/reads/', include('reads.api')),
    url(r'^.*', include('reads.urls'))
    # url(r'^.*$', RedirectView.as_view(url='reads/', permanent=False), name='index')
]

reads/models.py
from django.db import models

class Book(models.Model):
    
    title = models.CharField(max_length=255)
    link = models.CharField(max_length=2000)
    ASIN = models.CharField(max_length=20)
    large_image = models.CharField(max_length=255, null=True)
    medium_image = models.CharField(max_length=255, null=True)
    small_image = models.CharField(max_length=255, null=True)
    tiny_image = models.CharField(max_length=255, null=True)
    rank = models.IntegerField(null=True)
    product_group = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.title + ' : ' + self.ASIN

class Comment(models.Model):
    book = models.ForeignKey(Book, related_name='comments', on_delete=models.CASCADE)
    text = models.TextField()
    link = models.CharField(max_length=255)
    score = models.IntegerField(null=True)
    date_time = models.DateTimeField(null=True)
    user = models.CharField(max_length=100, null=True)
    source = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.link

reads/views.py
from .models import Book
from .serializers import BookSerializer
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework import permissions

from django.http import HttpResponse, Http404
from django.shortcuts import get_object_or_404, render

from .models import Book

def index(request):
    latest_book_list = Book.objects.exclude(title='unprocessed').order_by('rank')[:20]
    context = {'latest_book_list': latest_book_list}
    return render(request, 'reads/index.html', context)

def detail(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, 'reads/detail.html', {'book': book})

class BookDetail(APIView):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    """
    Retrieve, update or delete a book instance.
    """
    def get_object(self, pk):
        try:
            return Book.objects.get(pk=pk)
        except Book.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        book = self.get_object(pk)
        serializer = BookSerializer(book)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = BookSerializer(data=request.data)
        if serializer.is_valid():
            serializer.create(serializer.validated_data)
            return Response(serializer.validated_data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def put(self, request, pk, format=None):
        book = self.get_object(pk)
        serializer = BookSerializer(book, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.validated_data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

reads/templates/reads/detail.html
{% load staticfiles %}
<head>
    <link href="https://fonts.googleapis.com/css?family=Rubik" rel="stylesheet">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/reads.css' %}">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-110200430-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-110200430-1');
    </script>
</head>
<body>
    <div class="container">
        <div class="row">
            <h1>Runner Reads</h1>
            <h3>Top products recommended for runners by runners across the Internet</h3>
        </div>
        <div class="row">
            <hr class="curved"/>
        </div>
        <div class="row top20">
            <div class="col-md-1">
                <a href="{{ book.link }}"><img src="{{ book.small_image }}"/></a>
            </div>
            <div class="col-md-11">
                <h4 class="title"><a href="{{ book.link }}">{{ book.title }}</a></h4>
            </div>
        </div>
        {% for comment in book.comments.all %}
        <div class="row callout callout-info">
            <div class="row top20">
                <div class="col-md-2">
                    Upvotes: {{ comment.score }}
                </div>
                <div class="col-md-10">
                    {{ comment.text }}
                </div>
            </div>
            <div class="row top20">
                <div class="col-md-10">
                    <a href="{{ comment.link }}">source</a>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="row top20"><a href="www.runnerreads.com">Back</a></div>
        <!-- Begin MailChimp Signup Form -->
        <link href="//cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css" rel="stylesheet" type="text/css">
        <style type="text/css">
            #mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; width:100%;}
            /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
            We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
        </style>
        <br/>
        <div class="row" id="mc_embed_signup">
        <form action="https://runnerreads.us17.list-manage.com/subscribe/post?u=55ace6f0a08975152a31a6cab&amp;id=b589641c30" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
            <div id="mc_embed_signup_scroll">
            <label for="mce-EMAIL">Looking for more running gear? Subscribe to the newsletter.</label>
            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
            <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_55ace6f0a08975152a31a6cab_b589641c30" tabindex="-1" value=""></div>
            <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
            </div>
        </form>
        </div>

        <!--End mc_embed_signup-->
    </div>
</body>

reads/templates/reads/index.html
{% load staticfiles %}
<head>
    <link href="https://fonts.googleapis.com/css?family=Rubik" rel="stylesheet">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/reads.css' %}">
    <script type="text/javascript" src="//downloads.mailchimp.com/js/signup-forms/popup/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script><script type="text/javascript">require(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us17.list-manage.com","uuid":"55ace6f0a08975152a31a6cab","lid":"b589641c30"}) })</script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-110200430-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-110200430-1');
    </script>
</head>
<body>
    <div class="container">
        <div class="row">
            <h1>Runner Reads</h1>
            <h3>Top products recommended for runners by runners across the Internet</h3>
        </div>
        <div class="row">
            <hr class="curved"/>
        </div>
        {% if latest_book_list %}
        
        {% for book in latest_book_list %}
        <div class="row top20">
            <div class="col-md-2"><a href="{{ book.link }}"><img src="{{ book.medium_image }}"/></a></div>
            <div class="col-md-10">
                <div>
                    <h4 class="title"><a href="{{ book.link }}">{{ book.title }}</a></h4>
                </div>
                <div>
                    <a href="{% url 'reads:detail' book.id %}">Comments</a>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="row"><p>No books are available.</p></div>
        {% endif %}
        <!-- Begin MailChimp Signup Form -->
        <link href="//cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css" rel="stylesheet" type="text/css">
        <style type="text/css">
            #mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; width:100%;}
            /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
            We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
        </style>
        <br/>
        <div class="row" id="mc_embed_signup">
        <form action="https://runnerreads.us17.list-manage.com/subscribe/post?u=55ace6f0a08975152a31a6cab&amp;id=b589641c30" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
            <div id="mc_embed_signup_scroll">
            <label for="mce-EMAIL">Looking for more running gear? Subscribe to the newsletter.</label>
            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
            <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_55ace6f0a08975152a31a6cab_b589641c30" tabindex="-1" value=""></div>
            <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
            </div>
        </form>
        </div>

        <!--End mc_embed_signup-->
    </div>
</body>